### ISSUE TITLE
Guest Actors

### ISSUE THREAD

**Issue by KarellenX** [pkscout/metadata.tvshows.themoviedb.org.python#8] opened 2020-09-14 06:39 UTC
Episodes show only regular cast on the Information Page which is the same as the actors shown in the TV Show information page.

Is it possible to have episode Guest Actors scraped for episodes.

**Comment by pkscout** [comment] 2020-09-14 15:42
Guest actors are in the API, and I think I even pull them. I just have to figure out where to put them in the list item so Kodi grabs them.

**Comment by pkscout** [comment] 2020-09-16 06:04
Mostly complete via e93da2602d786e6f4ab008aa3f76e9e198290453 and 90a0b71e1d837812ad8799bc420f51b07a5b3916. There is one oddity though (and I asked about it in the team Slack channel). If I add just guest stars to the episode, then in dialoginfo the guest stars are listed first with the main cast after that (they must get appended by Kodi at some point from the main show). That order seems wrong to me, so I add both the main cast and guest stars. That looks fine, except now the main cast is still appended at the end. I suspect so few people will get to the end of the guest star list to notice, but I don't like that. I'm leaving this open just to see if there are suggestions from the Slack channel.

**Comment by pkscout** [comment] 2020-09-16 14:35
Duplicate of main series cast fixed in 8d72f64d209c0c05deab63d9af00def845029199.  See my post in the team Slack, but it appears that guest stars first is the current behavior (and has been at least since Kodi 18), so I'm going to close this one. The Python scraper at least mimics the XML scraper in that aspect.

**Closed by pkscout** 2020-09-16 14:35 UTC
Labels: enhancement, help wanted
